'0.1.0-alpha.1':
    order: hierarchical
    key: resolution
    query_radius: 0.000277778  # 1 arcsec
    schema: catalogdb
    output_table: catalog
    start_node: tic_v8
    debug: true
    log_path: false
    disable_seqscan: true
    sample_region:
        - [270., 66.56, 5]    # North CVZ
        - [90., -66.56, 5]    # South CVZ
        - [45.0, 0.0, 5]      # Stripe-82-West
        - [135.0, 1.0, 5]     # eFEDS
        - [315.0, 0.0, 5]     # Stripe-82-East
    exclude: null
    tables:
        tic_v8:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: plx
            epoch: 2015.5
            skip: false
        gaia_dr2_source:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: parallax
            epoch: 2015.5
            skip: true
        legacy_survey_dr8:
            ra_column: ra
            dec_column: dec
            pmra_column: pmra
            pmdec_column: pmdec
            is_pmra_cos: true
            parallax_column: parallax
            epoch_column: ref_epoch
        twomass_psc:
            ra_column: ra
            dec_column: decl
            epoch_column: jdate
            epoch_format: jd
            skip: true
        tycho2:
            ra_column: ramdeg
            dec_column: demdeg
            pmra_column: pmra
            pmdec_column: pmde
            is_pmra_cos: true
            epoch: 2000.0
        ps1_g18:
            ra_column: ramean
            dec_column: decmean
        catwise:
            ra_column: ra_pm
            dec_column: dec_pm
            pmra_column: pmra
            pmdec_column: pmdec
            epoch: 2014.115  # MJD 56700
            parallax_column: par_pm
        guvcat:
            ra_column: ra
            dec_column: dec
        sdss_dr13_photoobj:
            ra_column: ra
            dec_column: dec
        kepler_input_10:
            ra_column: kic_ra
            dec_column: kic_dec
        glimpse:
            ra_column: ra
            dec_column: dec
        skymapper_dr1_1:
            ra_column: raj2000
            dec_column: dej2000
        gaia_qso:
            ra_column: raj2000
            dec_column: dej2000
        bhm_csc:
            ra_column: oir_ra
            dec_column: oir_dec
        gaia_dr2_wd_sdss:
            ra_column: ra
            dec_column: dec
        unwise:
            ra_column: ra
            dec_column: dec
